Support redis cluster as cache or database
gorse-io/gorse pull request #547
Opened 2022-08-31 04:22 UTC by 0xByteLeon

2022-08-31 14:00 UTC, zhenghaoz requested changes

2022-08-31 14:00 UTC, zhenghaoz commented on storage/cache/redis_cluster.go
> +	client *redis.ClusterClient
不需要再写一份`redis_cluster.go`，可以把`redis.go`的`redis.Client`替换成[`UniversalClient`](https://pkg.go.dev/github.com/go-redis/redis/v8#UniversalClient)，共享一份实现

2022-08-31 14:00 UTC, zhenghaoz commented on storage/data/redis_cluster.go
> +	client *redis.ClusterClient
data storage的Redis接口只用来测试，支持集群模型意义不大。如果要用Redis存数据的话需要RedisJSON，目前还没实现，所以不需要为data storage支持Redis集群

2022-08-31 14:00 UTC, zhenghaoz commented on storage/data/redis_cluster_test.go
> +func newMockRedisCluster(t *testing.T) *mockRedisCluster {
测试没过，既然data storage没有支持集群的意义，可以直接删了>_<

2022-08-31 14:00 UTC, zhenghaoz commented on storage/cache/redis_cluster_test.go
> +	redisDSN = env("REDIS_URI", "redis://127.0.0.1:6379/,")
如果将`redis.go`中的客户端改为[UniversalClient](https://pkg.go.dev/github.com/go-redis/redis/v8#UniversalClient)，那么只需要`redis_test.go`测试通过就行，不需要针对集群的测试啦

2022-08-31 14:00 UTC, zhenghaoz commented on storage/cache/database.go
> +		if strings.Contains(path, ",") {
现在的集群URL无法支持用户名和密码以及其他配置项。单机版客户端的配置项`redis.Options`可以使用`ParseURL`解析，但是通用客户端的配置项`redis,UniversalOptions`缺少解析函数，实际上可以实现一个`redis,UniversalOptions`解析函数，然后使用`redis,UniversalOptions`创建`redis,UniversalClient`就可以支持集群了。

2022-09-15 04:18 UTC, 0xByteLeon commented on storage/cache/database.go
> +		if strings.Contains(path, ",") {
我看了一下这个接口，应该是不能完全支撑Redis 的Cluster 模式，参考这个链接

> https://aws.amazon.com/cn/blogs/china/all-roads-lead-to-rome-use-go-redis-to-connect-amazon-elasticache-for-redis-cluster/

云服务商的Redis 是直接提供了一个域名，无法直接区分是cluster 或者 single node

2022-09-15 05:23 UTC, zhenghaoz commented on storage/cache/database.go
> +		if strings.Contains(path, ",") {
或者我们用`redis+cluster://`前缀进行识别（类似 https://github.com/redis/redis-rb/issues/887 ），但是需要自己解析一下URL，因为集群模式需要支持多IP地址。多地址的URL解析比较复杂，可以参考MongoDB客户端实现

https://github.com/mongodb/mongo-go-driver/blob/92f12ba78fda3414b12da221f029d769d343a910/mongo/options/clientoptions.go#L244

最终效果是集群模型和单机模型创建连接的代码不同，其他数据操作需要共享实现

2022-09-16 06:43 UTC, closed without merging