add CORS to rest server and config
gorse-io/gorse pull request #550
Opened 2022-09-02 12:19 UTC by NMathar

i have to add it because my frontend gave me some CORS errors. Feel free for some tests and let me know if i have something to change.

2022-09-02 13:34 UTC, zhenghaoz requested changes
Thanks for your contribution. There is some comments. :smile:

2022-09-02 13:34 UTC, zhenghaoz commented on config/config.go
> +		// {"master.http_cors_domains", "GORSE_MASTER_HTTP_CORS_DOMAINS"}, // TODO: check if array has to be parsed
Environment variables could be tested in `TestBindEnv`:

https://github.com/gorse-io/gorse/blob/55754ddae69c46023c358038f1e94b6a97d3f3ac/config/config_test.go#L132-L149

2022-09-02 13:34 UTC, zhenghaoz commented on config/config.go
> +	HttpCorsDomains   []string      `mapstructure:"http_cors_domains"`            // add allowed cors domains
Unit tests are required in `TestUnmarshal` :smile_cat:

2022-09-02 13:34 UTC, zhenghaoz commented on server/rest.go
> +	log.Logger().Info("http server cors domains: ", zap.String("domains", strings.Join(s.Config.Master.HttpCorsDomains, ",")))
These two logging lines could be combined into this line:

https://github.com/gorse-io/gorse/blob/55754ddae69c46023c358038f1e94b6a97d3f3ac/server/rest.go#L74-L75

2022-09-02 13:34 UTC, zhenghaoz commented on server/rest.go
> +	container.Filter(container.OPTIONSFilter)
It seems that OPTIONSFilter is no longer needed. Could you verify it?

https://github.com/emicklei/go-restful/issues/27#issuecomment-142142068

2022-09-02 13:34 UTC, zhenghaoz commented on config/config.toml.template
> +# AllowedDomainFunc is optional and is a function that will do the check
I think this comment is wrong:

```go
// AllowedMethods is either empty or has a list of http methods names. Checking is case-insensitive.
```

2022-09-02 13:34 UTC, zhenghaoz commented on server/rest.go
> +		ExposeHeaders:  []string{"X-Gorse-Header"},
`X-Gorse-Header` hasn't been used in Gorse. Could we remove it?

2022-09-05 12:23 UTC, NMathar commented
thanks for your input. i hope my changes works for you.

2022-09-05 12:30 UTC, zhenghaoz commented on server/rest.go
> +	log.Logger().Info("http server cors domains: ", zap.String("domains", strings.Join(s.Config.Master.HttpCorsDomains, ",")))
Sorry for my misleading comment. I mean we can write something like this:

```go
log.Logger().Info("start http server",
    zap.String("url", fmt.Sprintf("http://%s:%d", s.HttpHost, s.HttpPort)),
    zap.Strings("cors_methods", s.Config.Master.HttpCorsMethods),
    zap.Strings("cors_doamins", s.Config.Master.HttpCorsDomains))
```

2022-09-05 12:34 UTC, zhenghaoz requested changes

2022-09-05 12:34 UTC, zhenghaoz commented on config/config_test.go
> +	assert.Equal(t, []string{}, config.Master.HttpCorsMethods)
We could inject some values here:

https://github.com/gorse-io/gorse/blob/cb592edeced61928e65fd6b6f572519d8962e32a/config/config_test.go#L30-L33

So that we have values in tests.

2022-09-05 12:34 UTC, zhenghaoz commented on server/rest.go
> +		zap.String("url", fmt.Sprintf("http://%s:%d CORS-Methods: %s, CORS-Doamins: %s",
Sorry for my misleading comment. I mean we can write something like this:

```go
log.Logger().Info("start http server",
    zap.String("url", fmt.Sprintf("http://%s:%d", s.HttpHost, s.HttpPort)),
    zap.Strings("cors_methods", s.Config.Master.HttpCorsMethods),
    zap.Strings("cors_doamins", s.Config.Master.HttpCorsDomains))
```

2022-09-05 12:35 UTC, zhenghaoz commented
> thanks for your input. i hope my changes works for you.

thanks for your response. maybe a little bit change is needed :smiley:

2022-09-05 13:05 UTC, NMathar commented
no problem i learn a lot in go now ^^

2022-09-05 13:19 UTC, zhenghaoz approved these changes

2022-09-05 13:28 UTC, merged

2022-12-30 23:50 UTC, 1003n40 commented on server/rest.go
> +		zap.Strings("cors_doamins", s.Config.Master.HttpCorsDomains),
Domains*